springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  redis:
    host: ec2-43-202-86-53.ap-northeast-2.compute.amazonaws.com
    port: 6379
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mainprojectdb.cdb3cg1btqgy.ap-northeast-2.rds.amazonaws.com:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


cloud:
  aws:
    s3:
      bucket: main-project-junyoung
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secretKey: SDFJSDLKJFSDIFOJSDIFSDLFJSDKFJLSDJFLSDKJFSDIFJLJSDKJFSDLKJF
  access:
    expiration: 90000000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh