springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testdb?createDatabaseIfNotExist=true
    username: root
    password: 759802
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
