springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.31.44.214:3307/testdb?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


cloud:
  aws:
    s3:
      bucket: main-project-junyoung
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


jwt:
  secretKey: SDFJSDLKJFSDIFOJSDIFSDLFJSDKFJLSDJFLSDKJFSDIFJLJSDKJFSDLKJF
  access:
    expiration: 3600000000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh



