name: Build
on:
  push:
    branches:
      - fe-feat/page #빌드하고싶은 브랜치
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: |
          npm run install
        working-directory: ./
      - name: Npm Build
        run: |
          npm run build
        working-directory: ./
      - name: Deploy to S3
        uses: jaerin_Lee/s3-sync-action@fe-feat/page
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'dist'
