# .github/workflows/client.yml
name: client
on:
  push:
    branches:
      - fe-feat/page
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        run: npm run build
        working-directory: ./client
      - name: SHOW AWS CLI VERSION
        run: |
          aws --version
      - name: Deploy to S3
        uses: ./client/s3-sync-action@fe-feat/page
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'dist'
